from typing import Any, Dict, Optional


class Error(Exception): ...
class MemoryError(Error): ...
class ConfigError(Error): ...
class ParserError(Error): ...
class RuleError(Error): ...


class Lognorm:
    """liblognorm context"""

    def __init__(self, *, rules: str) -> None: ...
    def normalize(self, log: str, strip: bool = False) -> Optional[Dict[str, Any]]: ...
    def get_error(self) -> Optional[str]: ...
    @staticmethod
    def version() -> str: ...
